### ISSUE TITLE
http: multiple response.WriteHeader calls

### ISSUE THREAD

**Issue by kennykarnama** [gophercises/cyoa#11]
```	
if chapter, ok := h.s[path]; ok {
		err := h.t.Execute(w, chapter)
		if err != nil {
			log.Printf("%v", err)
			http.Error(w, "Something went wrong...", http.StatusInternalServerError)
		}
		return
	}
	http.Error(w, "Chapter not found.", http.StatusNotFound)
```

I think this line causes the multiple response writeHeader call
by adding else after checking the map, we could avoid it

**Comment by joncalhoun** [comment]
I'm not sure which part you are referring to.

If `ok == false` we don't go inside the if block and instead call `http.Error`, so there shouldn't be double writes there.

if `ok == true` we execute our template. This always results in a write, so there even if it errors the only real way to "prevent" that is to wrap the `http.ResponseWriter` with a custom implementation that defers that write and allows us to reset it.

Regardless of whether there is an error or not, we return so the `http.Error` outside the if block is never called.


Now if I was going to rewrite this I might consider doing this instead, but only so the "success" path says to the left, not for reasons you mentioned (which I don't think hold true).

```go
chapter, ok := h.s[path]
if !ok {
	http.Error(w, "Chapter not found.", http.StatusNotFound)
	return
}
err := h.t.Execute(w, chapter)
if err != nil {
	log.Printf("%v", err)
	http.Error(w, "Something went wrong...", http.StatusInternalServerError)
	return
}
```

**Comment by kennykarnama** [comment]
Ah, i forgot to write in my code the statement `return`. 
thanks. it is more clearer

**Comment by joncalhoun** [comment]
No worries, and yes that could definitely lead to a double write :)
