### ISSUE TITLE
Accessing gopher.json from another directory

### ISSUE THREAD

**Issue by BudhirajaMadhav** [gophercises/cyoa#21]
I don't understand, your `gopher.json` file is in the root directory(2 directories up) still  you are able to do open it directly form [here](https://github.com/gophercises/cyoa/blob/solution/cmd/cyoaweb/main.go#L23). How? Doesn't the `os.Open()` function open files form the same directory if only file name is mentioned.

**Comment by joncalhoun** [comment]
Filepaths are relative to where the code is run from, not where the source file is.

**Comment by BudhirajaMadhav** [comment]
Thanks!
