### ISSUE TITLE
gopher.json link could link to github's

### ISSUE THREAD

**Issue by lshaowei18** [gophercises/cyoa#6]
Hi, the gopher.json's link here : "See gopher.json for a real example of a JSON story. I find that seeing the real JSON file really helps answer any confusion or questions about the JSON format." leads to https://gophercises.com/exercises/gopher.json. 

Would it be better if we switch it to https://github.com/gophercises/cyoa/blob/master/gopher.json ?

**Comment by joncalhoun** [comment]
Thanks!
